server:
  port: 8886
logging:
  level:
    org.springframework.jdbc: TRACE
    com.zaxxer.hikari: TRACE  # HikariCP 로그
    org.hibernate.SQL: TRACE  # Hibernate SQL 로그 (JPA 사용 시)
spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.authservice.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  issuer: gauri7891@gmail.com
  secret_key: pyjWTd80kOTqOrK2lhYnztUIlS3v7VxD4z1iki2XCuX7wYcXpi8XMKU15BDIit9AdZUPYDRQm7Z4r5fLPNZ7Sg==