CREATE TABLE IF NOT EXISTS user (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      userId VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      userName VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL
);